imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
fos_elastica:
    serializer: ~
    clients:
        default: { url: http://localhost:9200/}
#        serializer: ~
    indexes:
        search:
            types:
                anuncio:
                    mappings:
                        title:
                            analyzer: custom_search_analyzer
                            type: string
                        price:
                            type: float
                        location: ~
                        publish_date:
                            type: date
                        tauenos:
                            type: integer
                        visits: 
                            type: integer
                        status: ~
                        keywords: 
                            type: string
                        categoryname: 
                            type: string
                            boost: 9
                            search_analyzer: custom_search_analyzer2
                            index_analyzer: custom_index_analyzer2
                        subcategoryname:
                            type: string
                            boost: 9
                            search_analyzer: custom_search_analyzer2
                            index_analyzer: custom_index_analyzer2
                    persistence:
                        elastica_to_model_transformer:
                            ignore_missing: true
                        driver: mongodb
                        model: Prodi\TauenoBundle\Document\Anuncio
                        listener:
                            insert: true
                            update: true
                            delete: true
                            is_indexable_callback: "isPublic"
#                            immediate: false
                        provider: ~
                        finder: ~
            settings:
              index:
                  analysis:
                    analyzer:
                        custom_search_analyzer:
                            type: custom
                            tokenizer: standard
                            filter   : [standard, worddelimiter, stopwords, snowball, lowercase, asciifolding]
                        custom_index_analyzer:
                            type: custom
                            tokenizer: nGram
                            filter   : [standard, worddelimiter, stopwords, snowball, lowercase, asciifolding]
                        custom_search_analyzer2:
                            type: custom
                            tokenizer: keyword
                        custom_index_analyzer2:
                            type: custom
                            tokenizer: keyword
                    filter:
                        stopwords:
                            type:      stop
                            stopwords: [_spanish_]
                            ignore_case : true
                        worddelimiter :
                            type:       word_delimiter
                            preserve_original: true
                    tokenizer:
                        nGram:
                          type:     nGram
                          min_gram: 10
                          max_gram: 20    
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: taueno
    document_managers:
        default:
            mappings:
                TauenoBundle: { type: annotation }