<?php

namespace Prodi\TauenoBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends DocumentRepository
{
}